### ISSUE TITLE
抢座失败

### ISSUE THREAD

**Issue by zy1404513038** [Albresky/HDU-Library-Master#6]
Run python main.py
配置文件解析成功。
登录成功
[2023-09-20 19:08:22+08:00][checkpoint B]未到任务执行时间，还差[3098]s，等待中...
[2023-09-20 20:00:00+08:00][plan[0]=****] 开始预约...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 108, in <module>
    run()
  File "main.py", line 81, in run
    res = master.run(plan)
  File "/home/runner/work/HDU-Library-Master/HDU-Library-Master/utils/master.py", line 222, in run
    res = self.session.post(url=url, data=data).json()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.

**Comment by Albresky** [comment]
> Run python main.py 配置文件解析成功。 登录成功 [2023-09-20 19:08:22+08:00][checkpoint B]未到任务执行时间，还差[3098]s，等待中... [2023-09-20 20:00:00+08:00][plan[0]=****] 开始预约... Traceback (most recent call last): File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 971, in json return complexjson.loads(self.text, **kwargs) File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/**init**.py", line 357, in loads return _default_decoder.decode(s) File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 108, in run() File "main.py", line 81, in run res = master.run(plan) File "/home/runner/work/HDU-Library-Master/HDU-Library-Master/utils/master.py", line 222, in run res = self.session.post(url=url, data=data).json() File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/requests/models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) Error: Process completed with exit code 1.

---

已尝试修复，**请更新仓库至最新**并检查运行结果，如果问题依然存在，欢迎在本楼继续回复，谢谢~
