### ISSUE TITLE
error（更新后出问题了）

### ISSUE THREAD

**Issue by Timpaniiiii** [Albresky/HDU-Library-Master#8]
Run python main.py
配置文件解析成功。
登录成功
[***0***-10-16 19:***6:***8+08:00][checkpoint B]未到任务执行时间，还差[***00***]s，等待中...
[***0***-10-16 ***0:00:00+08:00][plan[0]=****] 开始预约...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/***.8.18/x64/lib/python***.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/***.8.18/x64/lib/python***.8/json/__init__.py", line ***57, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/***.8.18/x64/lib/python***.8/json/decoder.py", line ***7, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/***.8.18/x64/lib/python***.8/json/decoder.py", line ***55, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 117, in <module>
    run()
  File "main.py", line 85, in run
    res = master.run(plan)
  File "/home/runner/work/HDU-Library-Master/HDU-Library-Master/utils/master.py", line ***4***, in run
    res = res.json()
  File "/opt/hostedtoolcache/Python/***.8.18/x64/lib/python***.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.

**Comment by zy1404513038** [comment]
兄弟，我懂你

**Comment by Albresky** [comment]
请同步仓库至最新，谢谢

**Comment by Timpaniiiii** [comment]
> 请同步仓库至最新，谢谢

配置文件解析成功。
登录成功
[2023-11-07 19:27:16+08:00][checkpoint B]未到任务执行时间，还差[1964]s，等待中...
[2023-11-07 20:00:00+08:00][plan[0]=****] 开始预约...
请求失败，状态码错误，status_code=502
[2023-11-07 20:00:25+08:00]plan[0]=****] 预约结果：无响应

**Comment by Albresky** [comment]
> > 请同步仓库至最新，谢谢
> 
> 配置文件解析成功。 登录成功 [2023-11-07 19:27:16+08:00][checkpoint B]未到任务执行时间，还差[1964]s，等待中... [2023-11-07 20:00:00+08:00][plan[0]=**] 开始预约... 请求失败，状态码错误，status_code=502 [2023-11-07 20:00:25+08:00]plan[0]=**] 预约结果：无响应

---

自图书馆系统更新之后，不知道为啥就会随机地返回502。后续我再适配一下。
